### PR TITLE
feat: Add donation instructions

### LINKED ISSUE #21: Add SchoolCashOnline donation instructions

### PR DESCRIPTION
**Pull request by willuhmjs**

### CODE REVIEW

**Review by tristan-f-r — APPROVED** [review]
LGTM! Only suggestion from a technical side would be to avoid using CSS in `app.html` and move it to a separate global stylesheet, but that's for a separate refactor and doesn't need to be done here. @CoasterFan5 will do the visual & content review.

**Review by CoasterFan5 — APPROVED** [review]
LGTM, however, the wording of donation quantities could be more clear.

**Comment by willuhmjs** [comment]
> LGTM, however, the wording of donation quantities could be more clear. 

Feel free to make a commit that clarifies the instructions.

**Comment by tristan-f-r** [comment]
> suggestion

caw caw

**Review by CoasterFan5 — APPROVED** [review]
LGTM

**Pull request merged**
