### PR TITLE
feat: create page for sirens

### LINKED ISSUE #24: Add LHS sirens page
Will require chores to ensure component reusability.

### PR DESCRIPTION
**Pull request by willuhmjs**

### CODE REVIEW

**Comment by tristan-f-r** [comment]
Are they making it? Or was it assigned for us to do? (Also, again, please don't do early reviews -- it ruins the chance for people to review it when the code is actually there).

**Comment by willuhmjs** [comment]
> Are they making it? Or was it assigned for us to do?

The team mentor wanted us to do it. Please keep this PR clean and resolve any conflicts using organizational communications.

**Review by CoasterFan5 — APPROVED** [review]
lgtm

**Review by tristan-f-r — COMMENTED** [review]
​

**Comment by willuhmjs** [comment]
> Also, again, please don't do early reviews -- it ruins the chance for people to review it when the code is actually there.

Sorry, I will be sure to assign *you* as a reviewer when I am done from now on.

**Comment by willuhmjs** [comment]
lol

**Pull request merged**
